# Rubocop configuration for rails-ai project
#
# NOTE: We do NOT use rubocop-rails-omakase because:
# - This is NOT a Rails application (it's a documentation/tooling project)
# - rubocop-rails-omakase is for Rails apps with models/controllers/views
# - This project has custom needs (heavy test infrastructure, markdown files)
# - Our rubocop-setup skill recommends omakase for Rails apps, not this project

# Load custom cops (TEAM_RULES.md Rule #20)
require:
  - ./lib/rails_ai/cops/style/nested_bracket_access.rb

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/ci' # Bash script, not Ruby

# Style preferences
Style/Documentation:
  Enabled: false # Don't require class documentation for test files

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Hash access patterns (TEAM_RULES.md Rule #20)
Style/HashFetchChain:
  Enabled: true

Style/DigChain:
  Enabled: true

# Custom cop: Nested bracket access detection (Rule #20 enhancement)
Style/NestedBracketAccess:
  Enabled: true
  Severity: warning  # Warn only, don't fail CI yet

# Layout preferences
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\s*#' # Allow long comments
    - '^\s*it .* do$' # Allow long test descriptions

# Metrics - be lenient for test files
Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'
    - 'test/support/**/*'  # Test support files (e.g., LLM adapter with streaming)
    - 'Rakefile'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/support/**/*'  # Complex streaming/IO logic acceptable in test infrastructure

Metrics/PerceivedComplexity:
  Exclude:
    - 'test/support/**/*'  # Complex streaming/IO logic acceptable in test infrastructure

Metrics/BlockNesting:
  Exclude:
    - 'test/support/**/*'  # Deep nesting acceptable in streaming IO handlers

# Minitest specific
Minitest/MultipleAssertions:
  Enabled: false # Allow multiple assertions in tests

Minitest/AssertInDelta:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: false # Custom failure messages are valid pattern

# Naming preferences for tests
Naming/PredicateMethod:
  Exclude:
    - 'test/**/*'  # expected_pass is a test fixture method, not a predicate

# Lint - suppress expected exceptions
Lint/SuppressedException:
  AllowComments: true
  Exclude:
    - 'test/support/**/*'  # Intentional for non-blocking IO in streaming
